language: python

os:
  - linux

sudo: false

matrix:
  fast_finish: true

python:
  - 3.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

install:
  - CC=gcc-4.8 CXX=g++-4.8 pip install -r requirements.txt
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  
script:  
  - pytest
  - flake8
